name: LiDARObstacleDetection
options:
  bundleIdPrefix: com.obstacle.detection
  deploymentTarget:
    iOS: 15.0
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    PRODUCT_BUNDLE_IDENTIFIER: com.obstacle.detection.lidar
    INFOPLIST_FILE: Info.plist
    TARGETED_DEVICE_FAMILY: 1
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    ENABLE_BITCODE: NO
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:
  LiDARObstacleDetection:
    type: application
    platform: iOS
    sources:
      - path: Sources
        name: Sources
    info:
      path: Info.plist
      properties:
        UIRequiredDeviceCapabilities: [arkit]
        NSCameraUsageDescription: "This app uses the camera and LiDAR scanner to detect obstacles in your environment and help you navigate safely."
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        LSRequiresIPhoneOS: true
        CFBundleDisplayName: LiDAR Detect
        UIRequiresFullScreen: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.obstacle.detection.lidar
        INFOPLIST_FILE: Info.plist
        ENABLE_BITCODE: NO
    preBuildScripts:
      - script: |
          if [ ! -f "${PROJECT_DIR}/LaunchScreen.storyboard" ]; then
            echo "Creating LaunchScreen.storyboard..."
            touch "${PROJECT_DIR}/LaunchScreen.storyboard"
          fi
        name: Create Launch Screen
        outputFiles:
          - $(PROJECT_DIR)/LaunchScreen.storyboard